### PR TITLE
Improve GitHub Actions CI

### PR DESCRIPTION
**Pull request by AlexWayfer**
1. Split RuboCop and RSpec tasks.
2. Test against different Ruby versions.

### CODE REVIEW

**Comment by AlexWayfer** [comment]
I see fails.

> Your bundle only supports platforms ["x86_64-darwin-19"] but your local platform
>  is x86_64-linux. Add the current platform to the lockfile with `bundle lock
>  --add-platform x86_64-linux` and try again.


#6 should be merged before it.

```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index a297031..4888a5d 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -69,6 +69,7 @@ GEM
 
 PLATFORMS
   x86_64-darwin-19
+  x86_64-linux
 
 DEPENDENCIES
   bundler (>=
```

(`Gemfile.lock` is always bad for gems :disappointed: )

**Comment by dmuneras** [comment]
😅 I was trying to catch up while I have internet. But checking PR from my phone is not my strength.

**Comment by AlexWayfer** [comment]
> sweat_smile I was trying to catch up while I have internet. But checking PR from my phone is not my strength.

No problem, dude, thank you for your activity here.

**Comment by AlexWayfer** [comment]
I've rebased the branch with #6 merged, all CI green now.

**Pull request merged**
